spring:
  application:
    name: soccer_team
  datasource:
    url: JDBC:mysql://localhost:3306/library
    username: root
    password: Mysql_2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
